version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_server
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: 'Y'
    ports:
      - '1433:1433' # Mapping SQL Server port
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - mssql_network

volumes:
  mssql_data:

networks:
  mssql_network:
